name: Build Release Win32

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
          - amd64_arm64

    steps:
      - uses: actions/checkout@v3

      - uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          toolset: "15.0"
          arch: x86
          uwp: false

      - name: Building
        shell: bash
        env:
          CXX: cl.exe
        run: |
          mkdir build
          cd build
          cmake -G "Visual Studio 14 2015" -A Win32 ..
          cmake --build . --config Release

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: "Debug"
          path: '${{github.workspace}}/build/Release'